name: Gatsby Publish

on:
  push:
    branches:
      - develop
  schedule:
    - cron:  '0 */4 * * *'

jobs:
  build:
    name: Build and publish gatsby site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
      - name: Slack Notification
        if: successs()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: landing-page-publish-error
          SLACK_COLOR: '#3278BD'
          SLACK_MESSAGE: 'Published OSS landing page :rocket:'
          SLACK_TITLE: OSS landing page
          SLACK_USERNAME: Github
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
